### ISSUE TITLE
Incorrect offset on NW pad when writing to DEF

### ISSUE THREAD

**Issue by RTimothyEdwards** [YosysHQ/padring#5]
Found another very minor bug.  This one shows up when the corner pad is not exactly square (as is the case for the I/O library I'm working with right now).

Line 102 of defwriter.cpp should have

    y -= item->m_lefinfo->m_sx;

not

   y -= item->m_lefinfo->m_sy;

Because the pad is rotated 270 degrees, the Y offset must be equal to the cell width, not the cell height.

**Comment by trcwm** [comment]
Fixed.

**Comment by RTimothyEdwards** [comment]
Thanks!
